In [1]:
import numpy as np
import pandas as pd

In [15]:
X = np.array([[0,0],
             [0,1],
             [1,0],
             [1,1]])

# y = np.array([0, 0, 0, 1])

y = np.array([1, 0, 0, 0])

In [16]:
df_X = pd.DataFrame(X, columns = ['Feature_1', 'Feature_2'])
print("DataFrame X :")
df_X

DataFrame X :

   Feature_1  Feature_2
0          0          0
1          0          1
2          1          0
3          1          1

In [17]:
df_y = pd.DataFrame(y, columns=['Target'])
print("\nDataFrame y :")
df_y

DataFrame y :

   Target
0       1
1       0
2       0
3       0

In [18]:
np.random.seed(42)
w = np.random.randn(2)
b = np.random.randn()
print("Poids initiaux :", w)
print("Bias initial :", b)

Poids initiaux : [ 0.49671415 -0.1382643 ]
Bias initial : 0.6476885381006925

In [19]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [20]:
def predict(X, w, b):
    z = np.dot(X, w) + b
    return sigmoid(z)

In [21]:
def loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

In [22]:
learning_rate = 0.1
epochs = 2000

for i in range (epochs):
    y_pred = predict(X, w, b)
    dw = -2 * np.dot((y - y_pred) * y_pred * ( 1 - y_pred), X)  / len(X)
    db = -2 * np.mean((y - y_pred) * y_pred * ( 1 - y_pred))

    w -= learning_rate * dw
    b -= learning_rate * db

    if i % 100 == 0:
        print(f"Epoch {i}, Loss: {loss(y, y_pred)}")

Epoch 0, Loss: 0.4049317069448341
Epoch 100, Loss: 0.12574862594872263
Epoch 200, Loss: 0.10117952418952905
Epoch 300, Loss: 0.08571185292858366
Epoch 400, Loss: 0.07361753375366467
Epoch 500, Loss: 0.06398281159044975
Epoch 600, Loss: 0.05621512777004802
Epoch 700, Loss: 0.049870943095383494
Epoch 800, Loss: 0.0446242023440205
Epoch 900, Loss: 0.04023507689842614
Epoch 1000, Loss: 0.03652510765981665
Epoch 1100, Loss: 0.03335960386049141
Epoch 1200, Loss: 0.03063549233682454
Epoch 1300, Loss: 0.028272883174697262
Epoch 1400, Loss: 0.026209130668462966
Epoch 1500, Loss: 0.0243945852840494
Epoch 1600, Loss: 0.02278950983952989
Epoch 1700, Loss: 0.021361810495578993
Epoch 1800, Loss: 0.020085346779764507
Epoch 1900, Loss: 0.018938658798051608

In [23]:
y_pred =  predict(X, w, b)
print("Prédictions finales :", y_pred)
print("Classes prédites (seuil 0.5) :", (y_pred > 0.5).astype(int))

Prédictions finales : [0.79543651 0.12118349 0.12271906 0.00493619]
Classes prédites (seuil 0.5) : [1 0 0 0]

In [24]:
np.random.seed(42)
w = np.random.randn(2)
b = np.random.randn()

def bce(y_true, y_pred, eps=1e-12):
    return -np.mean(y_true * np.log(y_pred + eps) + (1 - y_true) * np.log(1 - y_pred + eps))

learning_rate = 0.5
for i in range(2000) : 
    y_pred = predict(X, w, b)
    dz =  y_pred - y
    w -= learning_rate * np.dot(dz, X) / len(X)
    b -= learning_rate * np.mean(dz)
    if i % 400 == 0:
        print(f"Epoch {i}, Loss: {bce(y, y_pred): .4f}")

print("Prédictions finales :", predict(X, w, b).round(3))

Epoch 0, Loss:  1.0348
Epoch 400, Loss:  0.0467
Epoch 800, Loss:  0.0235
Epoch 1200, Loss:  0.0156
Epoch 1600, Loss:  0.0116
Prédictions finales : [0.98  0.008 0.008 0.   ]